services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB      
    ports:
      - "54320:5432"
    volumes:
      - ./migration/docker-db-initial.sql:/docker-entrypoint-initdb.d/docker-db-initial.sql   
    env_file:
      - .env


  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    ports:
      - "54321:80"
    depends_on:
      - postgres
    env_file:
      - .env
